### ISSUE TITLE
404 page doesn't work nice

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer.github.io#21]
eg https://cs.symfony.com/1234/wertd
vs
https://cs.symfony.com/1234

**Comment by smnandre** [comment]
The relative link to the assets (css / images) is "`_static`" because i guess the 404 is generated once at root level.

```html
<link href="_static/css/code.css" rel="stylesheet" type="text/css" />
```

By using  an absolute `/_static/..`  it works, but i'm not sure if this should be handled in the template, via the `url_root` method, or another way

**Comment by keradus** [comment]
not sure as well, far away from Sphinx myself.
if you have code proposal how to solve it, please raise a PR 🙇🏻 
I will gladly review the `dist` changes

**Comment by smnandre** [comment]
Should be fixed in #22

**Comment by smnandre** [comment]
Back here to not pollute #22 with two different problems.

(copying this here to ease any future reading)

<img width="866" alt="Capture d’écran 2023-11-19 à 14 22 32" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer.github.io/assets/1359581/5db82705-e322-4b42-974e-c0e23bbf8afd">

**Comment by smnandre** [comment]
So.... as the 404.html is generated once, and then used in different depth in the site structure, there is no way to have relative URLs working as wanted there.

But i hear your comment about local development, so i suggest the following:
* touch nothing in the generated content pages
* make links absolute _only_ for the 404.html

Would that be an acceptable quick fix ?

**Comment by keradus** [comment]
I think it's OK for quick fix.
For proper fix, maybe `<base>` or ...
or we solve bigger issues like upgrade Sphinx from v3 or... stop using Sphinx and have proper SPA based on JS and json-based rules information (long shot, I'm not asking to focus on that)

**Comment by smnandre** [comment]
> proper SPA based on JS and json-based rules information (long shot, I'm not asking to focus on that) 

I won't be the best help for that :) 

Using the same stack / generators as Symfony Docs is out of the question ?

**Comment by keradus** [comment]
i'm not familiar with Sf Docs generator, not concluding on it myself.
