### ISSUE TITLE
website links to php files are broken

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer.github.io#3]
eg  PhpCsFixer\ConfigInterface

**Comment by keradus** [comment]
about dead links - exactly the probem for which I created this github issue

about <title> - can you elaborate on your concern here?

**Comment by smnandre** [comment]
> about <title> - can you elaborate on your concern here?

Hi! Thanks for the other fix!

The meta `<title>` tag is the same on every pages it seems, or at least on some.

Exemple: https://cs.symfony.com/doc/custom_rules.html

<img width="368" alt="Capture d’écran 2023-11-14 à 02 43 28" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer.github.io/assets/1359581/20ecaf79-2c49-4669-b097-0fc19cbf72d1">


Imho, it "should" be something like: 

```
<title>Custom Rules - PhpCsFixer</title>
```

This has two (**midly**) annoying effect:
* i cannot differenciate the page when i open multiple tags (or in my history, favorite maganagement tools, etc..)
* it's sometimes harder to find those pages on Google (this one is not a good example)


<img width="433" alt="Capture d’écran 2023-11-14 à 02 46 21" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer.github.io/assets/1359581/3cc25b71-dbfb-484e-9153-0a962c462427">

**Comment by keradus** [comment]
got you know. Then I consider it as separated feature request and not as bug report, especially bug report about broken links.

if you up for it, please send a PR with proposal.

**Comment by smnandre** [comment]
> got you know. Then I consider it as separated feature request and not as bug report, especially bug report about broken links.
> 
> if you up for it, please send a PR with proposal.

Of course, PR incoming then :)
