### ISSUE TITLE
Impact of #22

### ISSUE THREAD

**Issue by smnandre** [PHP-CS-Fixer/PHP-CS-Fixer.github.io#31]
Hi there!

I'm very curious to find out whether https://github.com/PHP-CS-Fixer/PHP-CS-Fixer.github.io/pull/22 had any significant impact on the website's traffic, and to what extent.

Feel free to get in touch by email or via Symfony Slack if that's more convenient for you.

**Comment by keradus** [comment]
Hey,
unfortunately no stats on that,
also GA was dropped for the project, ref https://github.com/PHP-CS-Fixer/PHP-CS-Fixer.github.io/pull/32
